In [15]:
import pandas as pd
import numpy as np

data = {
    'Student_ID': [1,2,3,4,5,6,7,8,9,10],
    'Gender': ['M','F','F','M','F','M','M','F','M','F'],
    'Study_Hours': [2, 5, 3, np.nan, 8, 1, 6, 2, 50, 4],  
    'Marks': [45, 78, 65, 50, 90, 30, np.nan, 55, 85, 60],
    'Attendance': [75, 88, 92, 60, 95, 50, 85, np.nan, 90, 80]
}

df = pd.DataFrame(data)
print(df)

   Student_ID Gender  Study_Hours  Marks  Attendance
0           1      M          2.0   45.0        75.0
1           2      F          5.0   78.0        88.0
2           3      F          3.0   65.0        92.0
3           4      M          NaN   50.0        60.0
4           5      F          8.0   90.0        95.0
5           6      M          1.0   30.0        50.0
6           7      M          6.0    NaN        85.0
7           8      F          2.0   55.0         NaN
8           9      M         50.0   85.0        90.0
9          10      F          4.0   60.0        80.0

In [16]:
print(df.isnull().sum())

Student_ID     0
Gender         0
Study_Hours    1
Marks          1
Attendance     1
dtype: int64

In [17]:
df['Study_Hours'].fillna(df['Study_Hours'].mean(), inplace=True)
df['Marks'].fillna(df['Marks'].mean(), inplace=True)
df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

C:\Users\Mukta\AppData\Local\Temp\ipykernel_1112\1519824250.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Study_Hours'].fillna(df['Study_Hours'].mean(), inplace=True)
C:\Users\Mukta\AppData\Local\Temp\ipykernel_1112\1519824250.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(df['Marks'].mean(), inplace=True)
C:\Users\Mukta\AppData\Local\Temp\ipykernel_1112\1519824250.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Attendance'].fillna(df['Attendance'].mean(), inplace=True)

In [18]:
df

   Student_ID Gender  Study_Hours  Marks  Attendance
0           1      M          2.0   45.0   75.000000
1           2      F          5.0   78.0   88.000000
2           3      F          3.0   65.0   92.000000
3           4      M          9.0   50.0   60.000000
4           5      F          8.0   90.0   95.000000
5           6      M          1.0   30.0   50.000000
6           7      M          6.0   62.0   85.000000
7           8      F          2.0   55.0   79.444444
8           9      M         50.0   85.0   90.000000
9          10      F          4.0   60.0   80.000000

In [19]:
# Study hours cannot be > 24
df.loc[df['Study_Hours'] > 24, 'Study_Hours'] = df['Study_Hours'].median()

In [20]:
def detect_outliers(col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    return df[(df[col] < lower) | (df[col] > upper)]

print(detect_outliers('Study_Hours'))
print(detect_outliers('Marks'))
print(detect_outliers('Attendance'))

Empty DataFrame
Columns: [Student_ID, Gender, Study_Hours, Marks, Attendance]
Index: []
Empty DataFrame
Columns: [Student_ID, Gender, Study_Hours, Marks, Attendance]
Index: []
   Student_ID Gender  Study_Hours  Marks  Attendance
5           6      M          1.0   30.0        50.0

In [21]:
df

   Student_ID Gender  Study_Hours  Marks  Attendance
0           1      M          2.0   45.0   75.000000
1           2      F          5.0   78.0   88.000000
2           3      F          3.0   65.0   92.000000
3           4      M          9.0   50.0   60.000000
4           5      F          8.0   90.0   95.000000
5           6      M          1.0   30.0   50.000000
6           7      M          6.0   62.0   85.000000
7           8      F          2.0   55.0   79.444444
8           9      M          4.5   85.0   90.000000
9          10      F          4.0   60.0   80.000000